### ISSUE TITLE
Custom background colour bottomsheet

### ISSUE THREAD

**Issue by superdiazzz** [lopspower/RateBottomSheet#10]
Hi thank you for creating this amazing library, btw i got black colour background in bottomsheet. How i can change this color at least i cant use my color resource for this. Thank you!

**Comment by lopspower** [comment]
Hello, you can change the entire Layout by redefining it directly in your project. So that the library always works correctly, we must keep the id of views:
https://github.com/lopspower/RateBottomSheet/blob/master/ratebottomsheet/src/main/res/layout/rate_bottom_sheet_layout.xml

**Comment by superdiazzz** [comment]
> Hello, you can change the entire Layout by redefining it directly in your project. So that the library always works correctly, we must keep the id of views:
> https://github.com/lopspower/RateBottomSheet/blob/master/ratebottomsheet/src/main/res/layout/rate_bottom_sheet_layout.xml

How can i connecting new rate_bottom_sheet layout to my rateBottomSheet. I didn't find costume layout in this library.

**Comment by lopspower** [comment]
You just have to copy paste the layout into your project. It will override the layout of the lib.
