### ISSUE TITLE
Calling from java instead of Kotlin

### ISSUE THREAD

**Issue by cerupcat** [lopspower/RateBottomSheet#2]
Is there a way to call 'showRateBottomSheetIfMeetsConditions' from java? Do you have an example of integrating with java instead of kotlin?

**Comment by lopspower** [comment]
You can call `showRateBottomSheetIfMeetsConditions` func like this:

```java
RateBottomSheet.Companion.showRateBottomSheetIfMeetsConditions(this);
```

And because this library it's write in Kotlin you need to add **kotlin-stdlib** dependency on your java project:
```grovy
 implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.3.61'
```
