### ISSUE TITLE
Click listener on dislike button

### ISSUE THREAD

**Issue by FelixMittermeier** [lopspower/RateBottomSheet#4]
Hi and first of all a huge thanks for the great library.

Currently I have one problem: when the user is asked if he likes the app or not, I am not able to define an action what to do if the user clicks the dislike button. I want to open a new activity where the user can input some reasons and hints for improvements etc.

Is this already possible or does it have to be integrated first?

Greetings

**Comment by lopspower** [comment]
Hi @FelixMittermeier thanks for your feedback.
I note your idea to add in the next version.

**Comment by lopspower** [comment]
It's now fix on the last version:
```groovy
implementation 'com.mikhaellopez:ratebottomsheet:1.1.0'
```
When calling `RateBottomSheet.showRateBottomSheetIfMeetsConditions(...)` you can choose to add another parameter of type `AskRateBottomSheet.ActionListener`; this allows you to implement 3 optional callbacks.
Here is how:

```kotlin
RateBottomSheet.showRateBottomSheetIfMeetsConditions(
    this,
    listener = object : AskRateBottomSheet.ActionListener {
        override fun onDislikeClickListener() {
            // Will be called when a click on the "I don't like" button is triggered
        }

        override fun onRateClickListener() {
            // Will be called when a click on the "Rate" button is triggered
        }

        /*override fun onNoClickListener() {
            // Will be called when a click on the "No thanks" button is triggered,
            // in this example is commented,
            // but each callback is optional and it's up to you whether to implement it or not!
        }*/
    }
)
```

Thanks @lukelorusso for your pull to request

**Comment by FelixMittermeier** [comment]
Thank you very much 👍 I am going to try it next week :-)
Have a nice day.

**Comment by YuanOnLine** [comment]
Hi, thanks a lot for the great library.
Seems that the listener is not being triggered despite it's defined as in your example in the code. Can you please check it? 
A suggestion: have you thought that if it can be customize the URL, you could use this library for ask for other things not only for rate the app? (open a web page for more info, etc.)
