### ISSUE TITLE
Wrong size when rotate device

### ISSUE THREAD

**Issue by goodibunakov** [lopspower/RateBottomSheet#5]
![Screenshot_2020-03-25-00-56-12-211_ru goodibunakov iremember](https://user-images.githubusercontent.com/12848175/77460541-cd00f180-6e33-11ea-8751-54fea6721820.jpg)
![Screenshot_2020-03-25-00-56-07-934_ru goodibunakov iremember](https://user-images.githubusercontent.com/12848175/77460544-ce321e80-6e33-11ea-8e67-c5c1fc9370ac.jpg)
![Screenshot_2020-03-25-00-55-59-678_ru goodibunakov iremember](https://user-images.githubusercontent.com/12848175/77460547-cecab500-6e33-11ea-8467-3ad0d66a69ce.jpg)
![Screenshot_2020-03-25-00-55-54-688_ru goodibunakov iremember](https://user-images.githubusercontent.com/12848175/77460549-cf634b80-6e33-11ea-8608-8fbb67f3823e.jpg)

**Comment by lopspower** [comment]
It's now fix on the last version:
```groovy
implementation 'com.mikhaellopez:ratebottomsheet:1.1.0'
```
