### ISSUE TITLE
IllegalStateException 

### ISSUE THREAD

**Issue by goodibunakov** [lopspower/RateBottomSheet#8]
Fatal Exception: java.lang.IllegalStateException
Can not perform this action after onSaveInstanceState

com.mikhaellopez.ratebottomsheet.AskRateBottomSheet$Companion.show$ratebottomsheet_release (AskRateBottomSheet.kt:16)

**Comment by lopspower** [comment]
Did you use the last version of the library ?
```groovy
implementation 'com.mikhaellopez:ratebottomsheet:1.1.0'
```
Because line 16 on this file version points to nothing.

**Comment by goodibunakov** [comment]
This bug was when version was lower than 1.1.0. With new version of library it not happen yet.

**Comment by lopspower** [comment]
If the problem recurs on the last version I reopen the ticket.
